import { Meta, StoryObj } from '@storybook/react-vite';
import { ReactNode } from '../../../node_modules/react';
declare const Box: ({ children, className, }: {
    children: ReactNode;
    className: string;
}) => import("react/jsx-runtime").JSX.Element;
declare const meta: Meta<typeof Box>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const P1: Story;
export declare const P2: Story;
export declare const P3: Story;
export declare const P4: Story;
export declare const P15: Story;
export declare const POr1: Story;
export declare const POr2: Story;
export declare const POr3: Story;
export declare const POr4: Story;
export declare const POr5: Story;
export declare const M1: Story;
export declare const M2: Story;
export declare const M3: Story;
export declare const M4: Story;
export declare const M15: Story;
export declare const MOr1: Story;
export declare const MOr2: Story;
export declare const MOr3: Story;
export declare const MOr4: Story;
export declare const MOr5: Story;
export declare const Combine: Story;
